# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  buildpacks: buildpacks/pack@dev:c2c0651
workflows:
  main:
    jobs:
      - buildpacks/build:
          image-name: nodefun
          builder: cnbs/sample-builder:alpine
          buildpack: buildpacks/hello-world
