# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  buildpacks: buildpacks/pack@dev:1dcd173
workflows:
  main:
    jobs:
      - buildpacks/build:
          working-directory: working-directory-test
          image-name: nodefun
          builder: cnbs/sample-builder:alpine
          buildpack: buildpacks/hello-world
          env-vars: FOO=BAR;NAME=bilbo;COLOR=red and green;URL=https://www.google.com;SINGLE
